sudo: required
services:
    - docker

before_install:
    - docker build -t arie/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true arie/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-291596715660"
    bucket_path: "docker-react"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
